= transcendence

== virtual environnement

-> https://docs.python.org/fr/3/library/venv.html

The venv module supports creating lightweight "virtual environments", each with their own independent set of Python packages installed in their site directories. A virtual environment is created on top of an existing Python installation, known as the virtual environment's "base" Python, and may optionally be isolated from the packages in the base environment, so only those explicitly installed in the virtual environment are available.

When used from within a virtual environment, common installation tools such as pip will install Python packages into a virtual environment without needing to be told to do so explicitly.

A virtual environment is (amongst other things):

* Used to contain a specific Python interpreter and software libraries and binaries which are needed to support a project (library or application). These are by default isolated from software in other virtual environments and Python interpreters and libraries installed in the operating system.

* Contained in a directory, conventionally either named venv or .venv in the project directory, or under a container directory for lots of virtual environments, such as ~/.virtualenvs.

* Not checked into source control systems such as Git.

* Considered as disposable -- it should be simple to delete and recreate it from scratch. You don't place any project code in the environment

* Not considered as movable or copyable -- you just recreate the same environment in the target location.

=== basic setup

* To create virtual Python environnement in a directorie named .venv using venv library module as a script
+
[,bash]
----
python3 -m venv /path/to/new/virtual/environment
----

* activate the virtual environment with :
+
[,bash]
----
. .venv/bin/activate
----
+
* you can deactivate a virtual environment by typing deactivate in your shell
+
[,bash]
----
deactivate
----
+
You should go through this activation process any time you want to work on your project

=== pushing to git

-> https://pip.pypa.io/en/stable/cli/pip_freeze/

For different reasons, this virtual environment might not entirely work with a different path on a different machine. It is then not a very good idea to push it all on a git server. A good solution is to use the freeze command from pip :

[,bash]
----
python3 -m pip freeze
----

It will list all installed packages. You can put this list in a .txt file which can be used to install the said packages in another environment :

* create a file "requirements.txt" that you can easily put in your git repo
+
[,bash]
----
python3 -m pip freeze > requirements.txt
----

* use this same file to install in another env all the listed packages
+
[,bash]
----
python3 -m pip install -r requirements.txt
----


